# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.4-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: Examplepass14
    ports:
      - "5440:5432"
    expose:
      - 5432

  backend:
    build:
      context: backend
      target: builder
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: Examplepass14
    ports:
      - "8000:8000"
    depends_on:
      - db
    # image: python:3.10.13-bookworm
